import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // An underscore-prefixed binding is a deliberate discard here (rest-destructuring
  // strips the `[tournament]` block for the chipEV twin solve). Without this, four
  // intentional discards are warnings and a real unused variable is lost among them.
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", ignoreRestSiblings: true },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    // Vercel build output, generated by `vercel build`. Not ours to lint.
    ".vercel/**",
    "build/**",
    "next-env.d.ts",
    // wasm-pack generated glue, copied in by scripts/sync-wasm.mjs. Not ours to lint.
    "vendor/**",
    "public/wasm/**",
  ]),
]);

export default eslintConfig;
